package io.github.swampus;
/**
 * Mock class generated by AI that contains access-controlled methods.
 */
public class SyntheticAIExample {

    public static void main(String[] args) {
        AIModule module = new AIModule();
        ShelduerClient shelduerClient = new ShelduerClient();
        //Ai register key of allow-access
        shelduerClient.allow("ai.retrain");

        System.out.println("Trying to retrain...");
        if (shelduerClient.isAccessAllowed("ai.retrain")) {
            module.retrain();
        } else {
            System.out.println("[DENIED] Access to retrain is blocked.");
        }

        shelduerClient.block("ai.retrain");

        System.out.println("Trying to retrain again...");
        if (shelduerClient.isAccessAllowed("ai.retrain")) {
            module.retrain();
        } else {
            System.out.println("[DENIED] Access to retrain is blocked.");
        }
    }

    public static class AIModule {

        @AccessControlled("ai.retrain")
        public void retrain() {
            System.out.println("🧠 [AIModule] Retraining model...");
        }

        @AccessControlled("ai.internal.data")
        private String secretData = "classified";
    }
}
